### PR TITLE
fix(Model): add deprecated convert model meshes

### PR DESCRIPTION
**Pull request by BotellaA**

### CODE REVIEW

**Review by MelchiorSchuh — APPROVED** [review]
The OPENGEODE_MODEL_DEPRECATED_EXPORT keyword also replaces the opengeode_model_api ?

**Comment by BotellaA** [comment]
> The OPENGEODE_MODEL_DEPRECATED_EXPORT keyword also replaces the opengeode_model_api ?

yes, a combination of export and deprecation

**Pull request merged**
