### PR TITLE
fix(VertexCycle): expose sort only function

### PR DESCRIPTION
**Pull request by BotellaA**

### CODE REVIEW

**Review by panquez — APPROVED** [review]
Is polygon_sort the right name ? What About a VertexCycle of 2 elements ?

**Comment by BotellaA** [comment]
> Is polygon_sort the right name ? What About a VertexCycle of 2 elements ?

It is not necessary for 2 elements. I really meant polygon and not VertexCycle.

**Comment by panquez** [comment]
> > Is polygon_sort the right name ? What About a VertexCycle of 2 elements ?
> 
> It is not necessary for 2 elements. I really meant polygon and not VertexCycle.

I really do not understand the difference betwwen polygon and VertexCycle. If I don't I suppose other people may not understand.

**Pull request merged**
